// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/dch1228/gobestpractices/layout/internal/biz"
	"github.com/dch1228/gobestpractices/layout/internal/conf"
	"github.com/dch1228/gobestpractices/layout/internal/data"
	"github.com/dch1228/gobestpractices/layout/internal/server"
	"github.com/dch1228/gobestpractices/layout/internal/service"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"go.opentelemetry.io/otel/trace"
)

// Injectors from wire.go:

func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger, traceTracerProvider trace.TracerProvider) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	todoRepo := data.NewTodoRepo(dataData, logger)
	todoUsecase := biz.NewTodoUsecase(todoRepo, logger)
	todoService := service.NewTodoService(todoUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, logger, traceTracerProvider, todoService)
	app := newApp(logger, grpcServer)
	return app, func() {
		cleanup()
	}, nil
}
