// Code generated by protoc-gen-go-errors. DO NOT EDIT.

package v1

import (
	fmt "fmt"
	errors "github.com/go-kratos/kratos/v2/errors"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
const _ = errors.SupportPackageIsVersion1

func IsUNKNOWN(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_UNKNOWN.String() && e.Code == 500
}

func ErrorUNKNOWN(format string, args ...interface{}) *errors.Error {
	return errors.New(500, ErrorReason_UNKNOWN.String(), fmt.Sprintf(format, args...))
}

func IsTodoNotFound(err error) bool {
	e := errors.FromError(err)
	return e.Reason == ErrorReason_TODO_NOT_FOUND.String() && e.Code == 404
}

func ErrorTodoNotFound(format string, args ...interface{}) *errors.Error {
	return errors.New(404, ErrorReason_TODO_NOT_FOUND.String(), fmt.Sprintf(format, args...))
}
